[project]
name = "hfendpoint"
version = "0.1.0"
description = "hfendpoint lib"
authors = [
    { name = "angt", email = "angt@hf.co" }
]
requires-python = ">=3.12"
dependencies = [
    "msgpack",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
