name: Rust Static Build

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:
  BINARY_NAME: hfendpoint

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}

    - name: Setup Zig
      run: sudo snap install zig --classic --beta

    - name: Build
      id: build
      run: |
        cargo install cargo-zigbuild
        cargo zigbuild --release --target ${{ matrix.target }}
        target="${{ matrix.target }}"
        name="hfendpoint-${target%%-*}-linux"
        cp "target/${{ matrix.target }}/release/hfendpoint" "$name"
        gzip -9 "$name"
        echo "asset_name=$name.gz" >> $GITHUB_OUTPUT

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-asset-${{ matrix.target }}
        path: ${{ steps.build.outputs.asset_name }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          gh release create "$RELEASE_VERSION" release-assets/*/*.gz \
             --title "secret ${RELEASE_VERSION#v}" \
             --notes "Release based on tag ${RELEASE_VERSION}"
